name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up Python 3.12
    uses: actions/setup-python@v5
    with:
     python-version: '3.12'
  - run: pip install flake8
  - run: pip install flake8-import-order
  - run: pip install mypy
  - run: flake8 embedding_converter face_swapper
  - run: mypy embedding_converter face_swapper
 test:
  strategy:
   matrix:
    os: [ macos-latest, ubuntu-latest, windows-latest ]
  runs-on: ${{ matrix.os }}
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up Python 3.12
    uses: actions/setup-python@v5
    with:
     python-version: '3.12'
  - run: pip install torch torchvision
  - run: pip install pytest
  - run: pytest
