name: ci

on: [ push, pull_request ]

jobs:
 lint:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up Python 3.10
    uses: actions/setup-python@v5
    with:
     python-version: '3.10'
  - run: pip install flake8
  - run: pip install flake8-import-order
  - run: pip install mypy
  - run: flake8 embedding_forge face_swapper
  - run: mypy embedding_forge face_swapper
